b = imread("barbara.jpg");
l = imread("lena.jpg");
B = fft2(b);
L = fft2(l);
phaseB = angle(B);
phaseL = angle(L);
absB = abs(B);
absL = abs(L);
BphaseL = absB * exp(1i * phaseL);
LphaseB = absL * exp(1i * phaseB);
bl = real(ifft2(BphaseL));
lb = real(ifft2(LphaseB));
imshow(bl, []);
figure;
imshow(lb, []);