f = imread("quadrati.png");
gray = rgb2gray(f); 
noise = imnoise(gray);
F = fft2(gray);
Fnoise = fft2(noise);
HighPass = Fnoise;
[a,b] = size(HighPass);
dist = distmatrix(a,b);
sigma = 30;
H_gau=exp(-(dist.^2)/(2*(sigma^2)));
High_gau = 1 - H_gau;
GaussianFiltered = Fnoise .* High_gau;
imgh_rec_gau = real(ifft2(GaussianFiltered));
imshow(imgh_rec_gau, []);
figure;
H_gau=exp(-(dist.^2)/(2*(sigma^2)));
GaussianFiltered = Fnoise .* H_gau;
img_rec_gau = real(ifft2(GaussianFiltered));
imshow(img_rec_gau, []);
